apiVersion: v1
kind: Service
metadata:
  name: selenium-hub
spec:
  selector:
    app: selenium-hub
  ports:
  - name: grid-ui
    port: 4444
    targetPort: 4444
  - name: eventbus-publish
    port: 4442
    targetPort: 4442
  - name: eventbus-subscribe
    port: 4443
    targetPort: 4443